@echo off
mkdir "%~dp0\DataLocal\"
cd "%~dp0\DataLocal\"
py "%~dp0dec5.py" "%~dp0DataLocal.list" "%~dp0DataLocal.pack"
mkdir "%~dp0\ImageDataLocal\"
cd "%~dp0\ImageDataLocal\"
py "%~dp0dec5.py" "%~dp0ImageDataLocal.list" "%~dp0ImageDataLocal.pack"
mkdir "%~dp0\ImageLocal\"
cd "%~dp0\ImageLocal\"
py "%~dp0dec5.py" "%~dp0ImageLocal.list" "%~dp0ImageLocal.pack"
mkdir "%~dp0\MapLocal\"
cd "%~dp0\MapLocal\"
py "%~dp0dec5.py" "%~dp0MapLocal.list" "%~dp0MapLocal.pack"
mkdir "%~dp0\NumberLocal\"
cd "%~dp0\NumberLocal\"
py "%~dp0dec5.py" "%~dp0NumberLocal.list" "%~dp0NumberLocal.pack"
mkdir "%~dp0\resLocal\"
cd "%~dp0\resLocal\"
py "%~dp0dec5.py" "%~dp0resLocal.list" "%~dp0resLocal.pack"
mkdir "%~dp0\UnitLocal\"
cd "%~dp0\UnitLocal\"
py "%~dp0dec5.py" "%~dp0UnitLocal.list" "%~dp0UnitLocal.pack"
pause